# Exercises

It includes question for numpy

# 1. Import the numpy package under the name np

In [1]:
#importing module
import numpy as np

# 2. Print the numpy version and the configuration

In [7]:
#importing module
import numpy as np

#Return version of numpy
print("Version of numpy is : ", np.__version__)

#Return configuration of numpy
print(np.show_config())

Version of numpy is :  1.21.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/DELL/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/DELL/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/DELL/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/DELL/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/DELL/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/DELL/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/DELL/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/DELL/anaconda3\\Library\\include']
Supported SIMD extensions in t

# 3. Create a null vector of size 10

In [9]:
#importing module
import numpy as np

#Creat null vectors 
Z = np.zeros(10)

print("Null vectors are : \n", Z)

Null vectors are : 
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


# 4. How to find the memory size of any array 

In [ ]:
arr size

# 5. How to get the documentation of the numpy add function from the command line?

In [15]:
import numpy as np
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

# 6. Create a null vector of size 10 but the fifth value which is 1

In [19]:
import numpy as np
#Creating null vector of size 10
x = np.zeros(10)

#Assign value to 4th index
x[4] = 1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


# 7. Create a vector with values ranging from 10 to 49

In [1]:
import numpy as np
#creating array of range 10 to 49
x = np.arange(10,50)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


# 8. Reverse a vector (first element becomes last)

In [21]:
import numpy as np
x = np.arange(10,50)

#Reverse the vector
x = x[::-1]
print(x)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


# 9. Create a 3x3 matrix with values ranging from 0 to 8

In [22]:
import numpy as np
x = np.arange(0,9).reshape(3, 3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


# 10. Find indices of non­zero elements from [1,2,0,0,4,0]

In [24]:
import numpy as np
x = np.nonzero([1,2,0,0,4,0])
print("Indices of nonzer elements are : ", x)

Indices of nonzer elements are :  (array([0, 1, 4], dtype=int64),)


# 11. Create a 3x3 identity matrix

In [27]:
#Using eye method
import numpy as np
x = np.eye(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [28]:
#Using identity
import numpy as np
x = np.identity(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# 12. Create a 3x3x3 array with random values

In [29]:
import numpy as np
#Create random array
x = np.random.random((3,3,3))
print(x)

[[[0.86300725 0.77944252 0.38867545]
  [0.36643993 0.69111643 0.52853632]
  [0.62017545 0.59429458 0.71927716]]

 [[0.01647119 0.33942798 0.20985555]
  [0.75024844 0.73934197 0.54510225]
  [0.96987647 0.83417599 0.61040781]]

 [[0.98246431 0.58969115 0.15271063]
  [0.10120718 0.33702953 0.9726417 ]
  [0.5668524  0.98911354 0.87306696]]]


# 13. Create a 10x10 array with random values and find the minimum and maximum values

In [32]:
import numpy as np

#Creating random array
x = np.random.random((10,10))

print("Our random array is : \n", x)

#Using min and max function
xmin = x.min()
xmax = x.max()

print("\nMinimum value of array is : ", xmin) 
print("\nMaximum value of array is : ", xmax)


Our random array is : 
 [[0.24738895 0.60977955 0.27126414 0.60261951 0.10270876 0.91773894
  0.20009339 0.22895133 0.85762676 0.64873522]
 [0.46817405 0.73171262 0.02522535 0.06817135 0.19187894 0.85494498
  0.5333833  0.90037166 0.50869542 0.37888859]
 [0.63199825 0.53400438 0.54400363 0.39449282 0.07763644 0.94269078
  0.08184485 0.56870426 0.48730261 0.77580902]
 [0.17674664 0.28045178 0.9355293  0.53781026 0.58479056 0.9252714
  0.9682735  0.66953078 0.03352884 0.4278268 ]
 [0.19300988 0.17336706 0.79940287 0.3142085  0.08171265 0.39998355
  0.09026741 0.8429897  0.85066561 0.20567335]
 [0.22115294 0.87955862 0.53767507 0.19135337 0.84130563 0.94487932
  0.16847475 0.60775828 0.44403151 0.36357257]
 [0.75705366 0.62820255 0.17153013 0.81664736 0.70753195 0.09009872
  0.0359709  0.82937015 0.62847678 0.66413222]
 [0.79411344 0.70398307 0.27761885 0.6388098  0.01316032 0.49154781
  0.35039655 0.97556463 0.01803626 0.0342144 ]
 [0.51789519 0.84508666 0.57688945 0.29564533 0.31741423 

# 14. Create a random vector of size 30 and find the mean value 

In [33]:
import numpy as np
#Creating random array
x = np.random.random(30)

print("Our random array is : \n", x)

#Calculating mean
m = x.mean()

print("\nMean of random array is : ", m)

Our random array is : 
 [0.66805    0.0947742  0.04530944 0.81067264 0.71192322 0.34295132
 0.1769242  0.07096666 0.86694636 0.27355445 0.24964658 0.19627748
 0.87812865 0.03247014 0.11201347 0.30100194 0.09820393 0.44359808
 0.29315924 0.98868283 0.57583623 0.34351354 0.34721043 0.35581818
 0.87157535 0.30673384 0.98115771 0.90655516 0.80895981 0.08709447]

Mean of random array is :  0.44132365149049513


# 15. Create a 2d array with 1 on the border and 0 inside

In [36]:
import numpy as np
#Firstly creating array all with 1
x = np.ones((10,10))
print("Array before : \n", x)

#Change inside value using row and column operation
x[1:-1,1:-1] = 0

print("\nArray after : \n", x)

Array before : 
 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

Array after : 
 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


# 16. How to add a border (filled with 0's) around an existing array?

pad() - The function returns the padded array of rank equal to the given array and the shape will increase according to pad_width

In [3]:
import numpy as np
#Creating random array of 5X5

arr = np.random.random((5,5))

arr = np.pad(arr,pad_width=(1,1),mode = 'constant',constant_values = 0)
arr

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ],
       [0.        , 0.04094088, 0.43211732, 0.96940527, 0.10695312,
        0.56334271, 0.        ],
       [0.        , 0.46519922, 0.99880661, 0.91319162, 0.49321601,
        0.73803306, 0.        ],
       [0.        , 0.88327589, 0.11212149, 0.31484106, 0.58992873,
        0.47388756, 0.        ],
       [0.        , 0.81908658, 0.80332406, 0.65310667, 0.41781125,
        0.08419828, 0.        ],
       [0.        , 0.37839388, 0.00340594, 0.49314406, 0.73403901,
        0.29800579, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ]])

# 17. What is the result of the following expression?

In [7]:
#nan stands for not a number

#importing module
import numpy as np

print(0 * np.nan)

#if you will check the equality of these it returns False
print(np.nan == np.nan)

# comparig infinite values with nan
print(np.inf > np.nan)

print(np.nan - np.nan)

print(0.3 == 3 * 0.1)

nan
False
False
nan
False


# 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

k- The default is 0. Use k>0 for diagonals above the main diagonal, and k<0 for diagonals below the main diagonal.

- The diag() function is used to extract a diagonal or construct a diagonal array.

In [39]:
import numpy as np
x = np.diag(1+np.arange(4),k=-1)
print(x)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [4]:
import numpy as np
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

numpy.unravel_index(indices, shape, order='C')

- numpy.unravel_index() function converts a flat index or array of flat indices into a tuple of coordinate arrays.

In [5]:
import numpy as np

#get the index of a maximum element in a numpy array along one axis
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


# 21. Create a checkerboard 8x8 matrix using the tile function

Syntax : numpy.tile(A, reps)
* A- array
* reps - The number of repetitions of A along each axis.
- Construct an array by repeating A the number of times given by reps.

In [8]:
import numpy as np
x = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 22. Normalize a 5x5 random matrix

In [4]:
import numpy as np
#Creating random array
X = np.random.random((5,5))

#Calculating min and max of array
Xmax = X.max()
Xmin = X.min()

#Formula for normalization
X = (X - Xmin)/(Xmax - Xmin)
print(X)

[[0.41270306 0.74577411 0.53129131 0.33460374 1.        ]
 [0.47283346 0.24935407 0.5478237  0.69002346 0.01942523]
 [0.97010287 0.37660134 0.08218788 0.51443646 0.27070873]
 [0.11244055 0.90055698 0.1723612  0.         0.79548375]
 [0.36996996 0.45944005 0.95847952 0.6442024  0.72732314]]


- In order to normalize a vector in NumPy, we can use the np.linalg.norm() function,

In [23]:
# Calculating a Vector Norm with NumPy
import numpy as np

# Generate an random Array
X = np.random.random((5,5))

# Calculate the vector norm
normalized_vector = X / np.linalg.norm(X)
print(normalized_vector)

2.4866983263683107
[[0.08769676 0.19553658 0.05556403 0.17753546 0.22813144]
 [0.15784147 0.1657302  0.33353424 0.08567789 0.17069294]
 [0.09599926 0.02443065 0.01867094 0.01684173 0.30711056]
 [0.03823063 0.26161513 0.2170434  0.39424076 0.00672938]
 [0.30873614 0.00838015 0.32729678 0.29549456 0.01577989]]


# 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)

In [34]:
import numpy as np
color = np.dtype([("r", np.ubyte, (1,)),
                ("g", np.ubyte, (1,)),
                ("b", np.ubyte, (1,)),
                ("a", np.ubyte, (1,))])
print(color)

[('r', 'u1', (1,)), ('g', 'u1', (1,)), ('b', 'u1', (1,)), ('a', 'u1', (1,))]


In [32]:
RGBA = np.dtype([('red',np.uint8),('green',np.uint8),('blue',np.uint8),('alpha',np.uint8)])
color = np.array((1,2,4,3),dtype = RGBA)
print(color['green'])
type(color)

2


numpy.ndarray

# 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [36]:
import numpy as np
#using dot product
x = np.dot(np.ones((5,3)), np.ones((3,2)))
print(x)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [38]:
#Creating random arrays
arr_1 = np.random.random((5,3))
arr_2 = np.random.random((3,2))
np.dot(arr_1,arr_2)

array([[1.85840844, 0.91012497],
       [1.07683803, 0.41644896],
       [1.55824775, 0.74306974],
       [0.8811993 , 0.50497267],
       [0.59458714, 0.13317637]])

# 25. Given a 1D array, negate all elements which are between 3 and 8, in place.

In [45]:
import numpy as np
#creating array with 11 elements
X = np.arange(11)
print("Array is : ", X)

#setting condition and multiply with -1
X[(3 < X) & (X <= 8)] *= -1

print("\nArray after negating elements  : ", X)

Array is :  [ 0  1  2  3  4  5  6  7  8  9 10]

Array after negating elements  :  [ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


# 26. What is the output of the following script?

In [46]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


# 27. Consider an integer vector Z, which of these expressions are legal?

In [55]:
import numpy as np
Z = arange(10)
print(Z**Z)
print("\n", 2 << Z >> 2)
print("\n",Z <- Z)
print("\n",1j*Z)
print("\n",Z/1/1)
print("\n",Z<Z>Z)

[        1         1         4        27       256      3125     46656
    823543  16777216 387420489]

 [  0   1   2   4   8  16  32  64 128 256]

 [False False False False False False False False False False]

 [0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j 0.+6.j 0.+7.j 0.+8.j 0.+9.j]

 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

# 28. What are the result of the following expressions?

In [57]:
import numpy as np
print(np.array(0) // np.array(0))
print(np.array(0) // np.array(0))
print(np.array(0) / np.array(0))

0
0
nan


C:\Users\DELL\AppData\Local\Temp\ipykernel_10720\2374626071.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
C:\Users\DELL\AppData\Local\Temp\ipykernel_10720\2374626071.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
C:\Users\DELL\AppData\Local\Temp\ipykernel_10720\2374626071.py:4: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))


# 29. How to round away from zero a float array ?

- The numpy. trunc() is a mathematical function that returns the truncated value of the elements of array

In [64]:
import numpy as np
#by using uniform elements
Z = np.random.uniform(-10,+10,10)

print(np.trunc(Z + np.copysign(0.5, Z)))

[  2.   8.   3. -10.  -2.   4.   9.   5.   9.  -8.]


In [63]:
#Create random array
arr = np.random.random((5,5))
print(arr)
#using round function
arr = np.round(arr,2)
print("\nArray after rounding \n",arr) 

[[0.18834772 0.37375366 0.13545577 0.62952876 0.91287777]
 [0.48964133 0.63610648 0.26891309 0.56559882 0.0583328 ]
 [0.53658867 0.99725928 0.52355349 0.31674748 0.08973926]
 [0.72973233 0.71057311 0.30836708 0.48990551 0.12557964]
 [0.51323652 0.99785391 0.90970849 0.15082052 0.33754391]]

Array after rounding 
 [[0.19 0.37 0.14 0.63 0.91]
 [0.49 0.64 0.27 0.57 0.06]
 [0.54 1.   0.52 0.32 0.09]
 [0.73 0.71 0.31 0.49 0.13]
 [0.51 1.   0.91 0.15 0.34]]


# 30. How to find common values between two arrays?

In [10]:
arr_1 = np.arange(9).reshape(3,3)
print("\nFirst array is : \n", arr_1)
arr_2 = np.array([[0,1,2],[3,4,5],[1,1,1]])
print("\nSecond array is : \n", arr_2)

common = np.intersect1d(arr_1, arr_2)
print("\nCommon values between two arrays are : ", common)



First array is : 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

Second array is : 
 [[0 1 2]
 [3 4 5]
 [1 1 1]]

Common values between two arrays are :  [0 1 2 3 4 5]


# 31. How to ignore all numpy warnings? 

- Below code give warning

In [8]:
import numpy as np
#It supprssed all warnings
np.seterr(all="ignore")
print(np.array(0) // np.array(0))


0


# 32. Is the following expressions true?

In [9]:
(np.sqrt(-1) == np.emath.sqrt(-1))

False

# 33. How to get the dates of yesterday, today and tomorrow?

- With the help of numpy.datetime64() method, we can get the date in a numpy array in a particular format i.e year-month-day by using numpy.datetime64() method.

-  Return the date in a format ‘yyyy-mm-dd’.

In [12]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("\nDate of yesterday is : ", yesterday)
today     = np.datetime64('today', 'D')
print("\nToday's date is : ", today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("\nTommorow's date is : ", tomorrow)


Date of yesterday is :  2023-01-07

Today's date is :  2023-01-08

Tommorow's date is :  2023-01-09


# 34. How to get all the dates corresponding to the month of July 2016?

In [14]:
Dates = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print("\nDate from July month are : \n", Dates)


Date from July month are : 
 ['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


# 35. How to compute ((A+B)*(-A/2)) in place (without copy)?

In [7]:
#import module
import numpy as np

#Create three arrays for performing operation using ones()
A = np.ones(3)*1
print("Our first array A is: \n", A)
B = np.ones(3)*2
print("\nOur second array B is: \n", B)
C = np.ones(3)*3
print("\nOur Third array C is: \n", C)

#add two array A and B first and result will store in B
#the out parameter create new objects
np.add(A,B,out=B)

#Division perform on A
np.divide(A,2,out=A)

#negative function return the negative of the input
np.negative(A,out=A)

#Performing dot product
print("\nFinal result for above equation is : \n", np.dot(A,B))


Our first array A is: 
 [1. 1. 1.]

Our second array B is: 
 [2. 2. 2.]

Our Third array C is: 
 [3. 3. 3.]

Final result for above equation is : 
 -4.5


# 36. Extract the integer part of a random array using 5 different methods

In [66]:
import numpy as np
Z = np.random.uniform(0,10,10)
#1 using operators
print(Z - Z%1)

#2 Using floor method
print(np.floor(Z))

#3 Using ceil method
print(np.ceil(Z)-1)

#4 Using astype method
print(Z.astype(int))

#5 Using trunc method
print(np.trunc(Z))

[1. 4. 7. 7. 8. 2. 3. 1. 4. 5.]
[1. 4. 7. 7. 8. 2. 3. 1. 4. 5.]
[1. 4. 7. 7. 8. 2. 3. 1. 4. 5.]
[1 4 7 7 8 2 3 1 4 5]
[1. 4. 7. 7. 8. 2. 3. 1. 4. 5.]


# 37. Create a 5x5 matrix with row values ranging from 0 to 4

In [10]:
import numpy as np
#Create array of 5x5 using zeros()
X = np.zeros((5,5))

#perform additon with array within range of 0 to 4
X += np.arange(5)
print("The created matris is : \n", X)

The created matris is : 
 [[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


# 38. Consider a generator function that generates 10 integers and use it to build an array

- generator - is a function that returns an iterator that produces a sequence of values when iterated over.

In [15]:
import numpy as np
#used generator function from python
def generate():
    #to return 10 values
    for x in range(10):
        yield x
x = np.fromiter(generate(),dtype=float,count=-1)
print("Our array is : \n", x)

Our array is : 
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


# 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded 

- The numpy.linspace() function returns number spaces evenly w.r.t interval.

In [17]:
import numpy as np
#using linspace
X = np.linspace(0,1,12,endpoint=True)[1:-1]
print("Values within interval is : \n", X)

Values within interval is : 
 [0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


# 40. Create a random vector of size 10 and sort it 

In [22]:
import numpy as np
#Create random vector
x = np.random.random(10)
#vectors before sorting
print("Original vectors : \n", x)
#sorting
x.sort()
print("\nVectors after sorting : \n", x)

Original vectors : 
 [0.51978173 0.72930493 0.7646328  0.98799435 0.27625608 0.83949948
 0.00500148 0.03903887 0.42905661 0.6137483 ]

Vectors after sorting : 
 [0.00500148 0.03903887 0.27625608 0.42905661 0.51978173 0.6137483
 0.72930493 0.7646328  0.83949948 0.98799435]


# 41. How to sum a small array faster than np.sum?

- add.reduce() is equivalent to sum()
- The given input array is reduced by applying the universal function recursively along a specified axis on consecutive elements.

In [19]:
import numpy as np
#creating array
x = np.arange(10)

print("Addition of array is :", np.add.reduce(x))

Addition of array is : 45


# 42. Consider two random array A anb B, check if they are equal

allclose() - Returns True if two arrays are element-wise equal within a tolerance.

In [21]:
import numpy as np
#Creating first random array with interger
A = np.random.randint(0,2,5)
print("First array is : \n", A)

#Creating second random array with interger
B = np.random.randint(0,2,5)
print("\nSecond array is : \n",B)

#Comparing array and give output
equal = np.allclose(A,B)
print("\nIs two arrays are equal : ", equal)

First array is : 
 [0 0 1 0 0]

Second array is : 
 [0 1 1 0 1]

Is two arrays are equal :  False


# 43. Make an array immutable (read­only)

- ndarray.flags - The flags object can be accessed dictionary-like (as in a.flags['WRITEABLE']), or by using lowercased attribute names (as in a.flags.writeable).

In [22]:
import numpy as np
X = np.zeros(10)
#Making array immutable
X.flags.writeable = False
X[0] = 1

ValueError: assignment destination is read-only

# 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates 

- The [:, :] stands for everything from the beginning to the end just like for lists.

- The difference is that the first : stands for first and the second : for the second dimension.

-  Cartesian Co-ordinate -  is used to locate the position of a point in a plane using two perpendicular lines.

- The numpy.arctan2() method computes element-wise arc tangent of arr1/arr2 choosing the quadrant correctly

In [1]:
import numpy as np
#creating random array
Z = np.random.random((10,2))

#It perform according to dimension we have pass
X,Y = Z[:,0], Z[:,1]

#used to determine the positive square-root of an array, element-wise
R = np.sqrt(X**2+Y**2)

#convert to cartesian cordinates
T = np.arctan2(Y,X)
print(R)
print(T)

[0.37322209 0.88788    1.05934047 0.82849359 0.86136691 0.97728494
 0.52642138 1.1151467  1.14236748 1.29011499]
[0.20283731 1.44092377 1.11506225 1.4369744  1.16150269 0.04391578
 0.66084541 1.05293149 0.79431515 0.79272283]


# 45. Create random vector of size 10 and replace the maximum value by 0

In [3]:
import numpy as np
#Create random array
x = np.random.random(10)
print("Our random array is : \n", x)

#replacing maximum value by 0
x[x.argmax()] = 0

print("\nArray after replacing maximum value with 0 : \n", x)

Our random array is : 
 [0.05997906 0.14106981 0.974737   0.05285787 0.23082807 0.06451562
 0.08479942 0.94854907 0.08921921 0.1370211 ]

Array after replacing maximum value with 0 : 
 [0.05997906 0.14106981 0.         0.05285787 0.23082807 0.06451562
 0.08479942 0.94854907 0.08921921 0.1370211 ]


# 46. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area

- meshgrid() - The numpy.meshgrid function is used to create a rectangular grid out of two given one-dimensional arrays representing the Cartesian indexing or Matrix indexing.

In [6]:
import numpy as np
#Creating array of 10x10
Z = np.zeros((10,10), [('x',float),('y',float)])

Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,10),
np.linspace(0,1,10))
print(Z)

[[(0.        , 0.        ) (0.11111111, 0.        )
  (0.22222222, 0.        ) (0.33333333, 0.        )
  (0.44444444, 0.        ) (0.55555556, 0.        )
  (0.66666667, 0.        ) (0.77777778, 0.        )
  (0.88888889, 0.        ) (1.        , 0.        )]
 [(0.        , 0.11111111) (0.11111111, 0.11111111)
  (0.22222222, 0.11111111) (0.33333333, 0.11111111)
  (0.44444444, 0.11111111) (0.55555556, 0.11111111)
  (0.66666667, 0.11111111) (0.77777778, 0.11111111)
  (0.88888889, 0.11111111) (1.        , 0.11111111)]
 [(0.        , 0.22222222) (0.11111111, 0.22222222)
  (0.22222222, 0.22222222) (0.33333333, 0.22222222)
  (0.44444444, 0.22222222) (0.55555556, 0.22222222)
  (0.66666667, 0.22222222) (0.77777778, 0.22222222)
  (0.88888889, 0.22222222) (1.        , 0.22222222)]
 [(0.        , 0.33333333) (0.11111111, 0.33333333)
  (0.22222222, 0.33333333) (0.33333333, 0.33333333)
  (0.44444444, 0.33333333) (0.55555556, 0.33333333)
  (0.66666667, 0.33333333) (0.77777778, 0.33333333)
  (0.8888

# 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij = 1/(xi ­ yj))

- Cauchy matrix - is an m×n matrix with elements aij

In [8]:
import numpy as np
X = np.arange(8)
Y = X + 0.5

#perform calculation for cauchy matrix
C = 1.0 / np.subtract.outer(X, Y)

#compute the determinant of the given square array 
result = np.linalg.det(C)
print("Cauchy Matrix value is : ", result)

Cauchy Matrix value is :  3638.1636371179666


# 48. Print the minimum and maximum representable value for each numpy scalar type

- iinfo() - function shows machine limits for integer types.
- finfo() - function shows machine limits for floating point types

In [12]:
import numpy as np
#iterate over different system limit
for dtype in [np.int8, np.int32, np.int64]:
    minimum = (np.iinfo(dtype).min)
    print("Minimum value for integer data type : ", minimum)
    maximum = np.iinfo(dtype).max
    print("Maximum value for integer data type : ", maximum)
    
for dtype in [np.float32, np.float64]:
    minim= np.finfo(dtype).min
    print("Minimum value for integer data type : ", minim)
    maxim = np.finfo(dtype).max
    print("Maximum value for integer data type : ", maxim)
    epsilon = np.finfo(dtype).eps
    print("Epsilion value is : ", epsilon)

Minimum value for integer data type :  -128
Maximum value for integer data type :  127
Minimum value for integer data type :  -2147483648
Maximum value for integer data type :  2147483647
Minimum value for integer data type :  -9223372036854775808
Maximum value for integer data type :  9223372036854775807
Minimum value for integer data type :  -3.4028235e+38
Maximum value for integer data type :  3.4028235e+38
Epsilion value is :  1.1920929e-07
Minimum value for integer data type :  -1.7976931348623157e+308
Maximum value for integer data type :  1.7976931348623157e+308
Epsilion value is :  2.220446049250313e-16


# 49. How to print all the values of an array?

In [20]:
import numpy as np
import sys
#Setting maxsize with system
np.set_printoptions(threshold=sys.maxsize)
x = np.ones((25,25))
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.

# 50. How to find the closest value (to a given scalar) in an array?

In [23]:
import numpy as np
x = np.arange(100)
print("Our array is : \n", x)

#getting uniform sample within range
v = np.random.uniform(0,100)
print("\nUniform distribution sample is : ", v)

#getting index absolute closest value
index = (np.abs(x-v)).argmin()

print("\nClosest value in given array is ", x[index])


Our array is : 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]

Uniform distribution sample is :  10.343009885818422

Closest value in given array is  10


# 51. How to tell if a given 2D array has null columns?

- numpy.any() : function tests whether any array elements along the mentioned axis evaluate to True.

In [4]:
import numpy as np
#Creating random array 3x10
x = np.random.randint(0,3,(3,10))
print("Our random array is: \n", x)
print((~x.any(axis=0)).any())

Our random array is: 
 [[0 2 0 0 1 1 2 1 2 2]
 [1 0 2 1 2 1 2 0 0 0]
 [2 0 0 1 1 0 0 0 1 2]]
False
