# NumPy Introduction

- It is python library
- It used for working with single and multidimensional array.
- NumPy stands For Numerical Python
- It is created by Travis Oliphant in 2005.
- It is partially written in Python but mostly written in C.

# Why we use NumPy

- In python we have list which serve purpose of array but they are slow process.
- Numpy aims to 50x times faster than python list.
- In python list we have to look for each element at different memory place but Array always store at continuous place in memory.
- NumPy mostly usefull in Data science
- It provides a high-performance multidimensional array object, and tools for working with these arrays. 
- It is the fundamental package for scientific computing with Python. 
- It is open-source software.

# Installing Numpy

We have to use following snippet

In [3]:
!pip install numpy

- To use Numpy we have always import it as follows

In [4]:
import numpy

- NumPy is usually imported under the np alias.

In [5]:
import numpy as np

# Creating Arrays

- The array object in NumPy is called ndarray.

- We can create a NumPy ndarray object by using the array() function.

* To create an ndarray, we can pass a list, tuple or any array-like object into the array() method.

In [13]:
import numpy as np
# here a is our python list
a = [4, 5, 3, 7, 8, 10]

# a1 become array from the given list
arr  = np.array(a)

print(arr)

[ 4  5  3  7  8 10]


* Use a tuple to create a NumPy array:

In [16]:
import numpy as np
tup = (1, 2, 3, 4, 5)
arr = np.array(tup)

print(arr)

[1 2 3 4 5]


In [19]:
arr

array([1, 2, 3, 4, 5])

# Basic array characteristics

It includes 
1. type
2. dimension of array
3. shape of array
4. size of array
5. types of element

# 1. type

In [20]:
import numpy as np
 
# Creating array object
arr = np.array( [[ 1, 2, 3],
                 [ 4, 2, 5]] )
 
# Printing type of arr object
print("Array is of type: ", type(arr))

Array is of type:  <class 'numpy.ndarray'>


# 2. dimension of array

In [33]:
import numpy as np
# Creating array object
arr = np.array([ 1, 2, 3])

arr1 = np.array( [[ 1, 2, 3], 
                 [ 4, 2, 5]] )

# Printing array dimensions (axes)
print("No. of dimensions of arr: ", arr.ndim)
print("No. of dimensions of arr1: ", arr1.ndim)

No. of dimensions of arr:  1
No. of dimensions of arr1:  2


# 3. shape of array

In [35]:
import numpy as np
arr = np.array([ 1, 2, 3])

arr1 = np.array( [[ 1, 2, 3], 
                 [ 4, 2, 5]] )
# Printing shape of array
print("Shape of array: ", arr.shape)
print("Shape of array1: ", arr1.shape)

Shape of array:  (3,)
Shape of array1:  (2, 3)


# 4. size of array

In [36]:
import numpy as np
arr = np.array([ 1, 2, 3])

arr1 = np.array( [[ 1, 2, 3], 
                 [ 4, 2, 5]] )
# Printing size (total number of elements) of array
print("Size of array: ", arr.size)
print("Size of array1: ", arr1.size)

Size of array:  3
Size of array1:  6


# 5. types of element

In [37]:
import numpy as np
arr = np.array([ 1, 2, 3])

arr1 = np.array( [[ 1, 2, 3], 
                 [ 4, 2, 5]] )

# Printing type of elements in array
print("Array stores elements of type: ", arr.dtype)
print("Array1 stores elements of type: ", arr1.dtype)

Array stores elements of type:  int32
Array1 stores elements of type:  int32


* desired data type of array

In [49]:
# dtype parameter 
import numpy as np 
arr = np.array([1, 2, 3], dtype = int) 
print("Data type of given array is : ", arr)

arr1 = np.array( [[ 1, 2, 3], 
                 [ 4, 2, 5]], dtype = complex )
print("Data type of given array is: ", arr1)

arr2 = np.array([1, 2, 3], dtype = float) 
print("Data type of given array is: ", arr2)

arr3 = np.array([1, 2, 0], dtype = bool) 
print("Data type of given array is: ", arr3)

Data type of given array is :  [1 2 3]
Data type of given array is:  [[1.+0.j 2.+0.j 3.+0.j]
 [4.+0.j 2.+0.j 5.+0.j]]
Data type of given array is:  [1. 2. 3.]
Data type of given array is:  [ True  True False]


# Higher Dimensional Arrays

* When the array is created, you can define the number of dimensions by using the ndmin argument.

In [39]:
import numpy as np
# Create an array with 5 dimensions and verify that it has 5 dimensions
arr = np.array([1, 2, 3, 4], ndmin=5)

print("Array is : ", arr)
print('number of dimensions :', arr.ndim)

Array is :  [[[[[1 2 3 4]]]]]
number of dimensions : 5


# NumPy Array Reshaping

- Reshaping means changing the shape of an array.

- The shape of an array is the number of elements in each dimension.

- By reshaping we can add or remove dimensions or change number of elements in each dimension.


1. Reshape From 1-D to 2-D
2. Reshape From 1-D to 3-D
3. Flattening the arrays

# 1. Reshape From 1-D to 2-D

- Convert the following 1-D array with 10 elements into a 2-D array.

- The outermost dimension will have 4 arrays, each with 3 elements:

In [60]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

newarr = arr.reshape(1, 10)

print("The 2 dimensional array is : \n", newarr)

The 2 dimensional array is : 
 [[ 1  2  3  4  5  6  7  8  9 10]]


We can also shape it according to column : 

In [62]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

newarr = arr.reshape(5, 2, order = 'C')

print("The 2 dimensional array is : \n", newarr)

The 2 dimensional array is : 
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


# 2. Reshape From 1-D to 3-D

* Convert the following 1-D array with 12 elements into a 3-D array.

* The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements:

In [57]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print("The 3D array is : \n", newarr)

The 3D array is : 
 [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


# 3. Flattening the arrays

- Flattening array means converting a multidimensional array into a 1D array.
- We can use reshape(-1) to do this.
- we can use ravel() method also

In [69]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print("The original array is : \n", arr)

newarr = arr.reshape(-1)

print("\nArray after flattening is : \n", newarr)

The original array is : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Array after flattening is : 
 [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [112]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print("The original array is : \n", arr)

flatten_array = arr.ravel()
print("\nFlatten array is : ", flatten_array)

The original array is : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Flatten array is :  [ 1  2  3  4  5  6  7  8  9 10 11 12]


- WE can pass order parameter for flattening array, bydefault it is order by rows

In [113]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print("The original array is : \n", arr)

flatten_array = arr.ravel(order = 'F')
print("\nFlatten array is : ", flatten_array)

The original array is : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Flatten array is :  [ 1  5  9  2  6 10  3  7 11  4  8 12]


# * Array Creation Routines

It includes following parameter to create array
1. empty
2. ones
3. zeros
4. arrange
6. linspace

# 1. numpy.empty()

- It creates an uninitialized array of specified shape and dtype

- numpy.empty(shape, dtype = float, order = 'C')

In [71]:
import numpy as np 
x = np.empty([4, 2], dtype = int) 
print(x)

[[          0           0]
 [-1510285232       32767]
 [          1           0]
 [         -1          -1]]


In [76]:
import numpy as np 
x = np.empty([7, 3], dtype = float, order = 'C') 
print(x)

[[8.59247481e-312 5.68175493e-322 0.00000000e+000]
 [0.00000000e+000             nan 1.16095484e-028]
 [8.44747281e+252 7.23796664e+159 1.28311626e+272]
 [9.34634029e+218 1.05223146e-153 6.32300944e+233]
 [2.20892684e+161 1.14115712e+243 9.38011961e-154]
 [8.29655075e-114 8.93168689e+271 4.98131536e+151]
 [1.94920670e-153 1.23971686e+224 2.59819219e-306]]


# 2. numpy.ones()

- Returns a new array of specified size, filled with ones.

- numpy.ones(shape, dtype = float, order = 'C')

In [84]:
# array of five ones. Default dtype is float 
import numpy as np 
arr = np.ones(5) 
print(arr)

[1. 1. 1. 1. 1.]


In [85]:
# array of 3 X 3 of datatype integer
import numpy as np 
arr = np.ones([3,3], dtype = int) 
print(arr)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


# 3. numpy.zeros()

- Returns a new array of specified size, filled with zeros.

- numpy.zeros(shape, dtype = float, order = 'C')

In [88]:
# singe dimension array of five zeros. Default dtype is float 
import numpy as np 
arr = np.zeros(5) 
print(arr)

[0. 0. 0. 0. 0.]


In [89]:
# array of 3 X 3 of datatype integer
import numpy as np 
arr = np.zeros((3, 3), dtype = int)  
print(arr)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


# 4. numpy.arrange()

- This function returns an ndarray object containing evenly spaced values within a given range.

- format - numpy.arange(start, stop, step, dtype)

- It always give single dimension array

In [94]:
# create array with 5 elements
import numpy as np 
arr = np.arange(5) 
print("\nA sequential array is :", arr)


A sequential array is : [0 1 2 3 4]


In [93]:
# start and stop parameters set 
import numpy as np 
#Create a sequence of integers from 10 to 30 with steps of 2
arr = np.arange(10,30,2) 
print("\nA sequential array with steps of 2:\n", arr)


A sequential array with steps of 2:
 [10 12 14 16 18 20 22 24 26 28]


# 5. numpy.linspace()

- This function is similar to arange() function. In this function, instead of step size, the number of evenly spaced values between the interval is specified.

- numpy.linspace(start, stop, num, endpoint, retstep, dtype)

In [98]:
import numpy as np 

#prints 10 values which are evenly spaced over the given interval 5-15
arr = np.linspace(5,15,10)

print("\nA sequential array with 10 values between 5 and 15 :\n", arr)


A sequential array with 10 values between 5 and 15 :
 [ 5.          6.11111111  7.22222222  8.33333333  9.44444444 10.55555556
 11.66666667 12.77777778 13.88888889 15.        ]


- endpoint = True by default, hence the stop value is included in the sequence. If false, it is not included

In [100]:
# endpoint set to false 
import numpy as np 
arr = np.linspace(10,20, 5, endpoint = False) 
print("\nA sequential array with 5 values between 10 and 20 :\n",arr)


A sequential array with 5 values between 10 and 20 :
 [10. 12. 14. 16. 18.]


# * NumPy Random

It includes following methods
1. random()
2. randint()
3. rand()
4. choice()

# 1.random()

- Create an array with random values

In [101]:
arr = np.random.random((2, 2))
print ("\nA random array:\n", arr)


A random array:
 [[0.69767357 0.55458978]
 [0.70458591 0.65287982]]


In [102]:
arr = np.random.random((2, 5))
print ("\nA random array:\n", arr)


A random array:
 [[0.00858437 0.55984189 0.74582852 0.40748759 0.20504533]
 [0.43967176 0.44266411 0.15891589 0.87257821 0.13961442]]


# 2. randint()

- The randint() method takes a size parameter where you can specify the shape of an array.

In [106]:
#Generate a 1-D array containing 5 random integers from 0 to 100:
import numpy as np

arr = np.random.randint(100, size=(5))

print("\nThe 1-D random array is : \n",arr)


The 1-D random array is : 
 [42 38 57 37 95]


In [28]:
#Generate a 1-D array containing 5 random integers from 0 to 100:
import numpy as np

arr = np.random.randint(100, size=(10,10))

print("\nThe random array is : \n",arr)


The random array is : 
 [[15  5 31 22  2 66 75 16  0 62]
 [ 1 37 10 99 82 99 88 62 92 96]
 [90 26 22 89 15 31 95 14 42 18]
 [84 89 56  7 87 61 41 85 84 56]
 [61 64 32 50 62 37 56 90 59 81]
 [18 74 98 57 85 18 86 37 59 55]
 [33 41 91 54 99 38 98 48 80 54]
 [13 99 23 95 13 64 97 20 36 70]
 [76 98  3 34 71  1 92 47  2 70]
 [45 51 15 75 42 78  5 16 95  5]]


# 3. rand()

- The rand() method also allows you to specify the shape of the array.

In [115]:
import numpy as np
# creating random array with default datatype float
arr = np.random.rand(5)

print("\nRandom number array is : \n", arr)


Random number array is : 
 [0.37779077 0.73272848 0.12946597 0.37765703 0.24569147]


- Generate a 2-D array with 3 rows, each row containing 5 random numbers:

In [117]:
import numpy as np
# creating random array with default datatype float
arr = np.random.rand(3, 5)

print("\nRandom 2-D array is : \n", arr)


Random 2-D array is : 
 [[0.77881226 0.90328898 0.11899552 0.07109912 0.32139356]
 [0.75073146 0.09951671 0.18873064 0.91210232 0.30602568]
 [0.09383484 0.52941406 0.04598477 0.22979217 0.3746314 ]]


# 4. choice()

- The choice() method allows you to generate a random value based on an array of values.

- The choice() method takes an array as a parameter and randomly returns one of the values.

In [119]:
import numpy as np
# It will return only one random number
x = np.random.choice([3, 5, 7, 9])

print("\nRandom number is : ", x)


Random number is :  9


In [123]:
import numpy as np
# creating random array with default datatype float
arr = np.random.rand(5)

print("\nRandom number array is : \n", arr)

x = np.random.choice(arr)

print("\nRandom number is : ", x)


Random number array is : 
 [0.27632695 0.26717078 0.5905044  0.72809446 0.21938548]

Random number is :  0.21938547889611582


- Generate a 2-D array that consists of the values in the array parameter (3, 5, 7, and 9):

In [127]:
import numpy as np
# creating random array with default datatype float
arr = np.random.rand(5)

print("\nRandom array is : \n ", arr)

x = np.random.choice(arr, size=(3, 5))

print("\nArray of size 3X5 is : \n", x)


Random array is : 
  [0.81148917 0.18086692 0.536034   0.65842367 0.68262588]

Array of size 3X5 is : 
 [[0.65842367 0.65842367 0.18086692 0.68262588 0.536034  ]
 [0.536034   0.65842367 0.536034   0.81148917 0.18086692]
 [0.68262588 0.536034   0.18086692 0.536034   0.536034  ]]


# * Random Permutations

- A permutation refers to an arrangement of elements.

It includes two methods
1. shuffle()
2. permutation()

# 1. shuffle()

- The shuffle() method makes changes to the original array.

In [23]:
import numpy as np

#Creating array
arr = np.array([1, 2, 3, 4, 5])
print("\nOriginal array is : \n", arr)

shfl = np.random.shuffle(arr)

print("\nArray after shuffling : \n", arr)


Original array is : 
 [1 2 3 4 5]

Array after shuffling : 
 [1 5 4 3 2]


# 2. permutation()

- The permutation() method returns a re-arranged array (and leaves the original array un-changed).

In [27]:
import numpy as np
#Creating array
arr = np.array([1, 2, 3, 4, 5])
print("\nOriginal array is : \n", arr)

p = np.random.permutation(arr)
print("\nArray after permutation : \n", p)


Original array is : 
 [1 2 3 4 5]

Array after permutation : 
 [1 3 5 2 4]


# * NumPy - Arithmetic Operations

It includes following methods
1. add
2. substract
3. multiply
4. divide
5. transpose

# Program for all above methods

- Dimension of both array must be same

In [141]:
import numpy as np

#Creating two arrays to perform operation in it.
#first array 
array1 = np.arange(1, 10).reshape(3,3)

print("\nOur first array is : \n", array1)

#second array
array2 = np.arange(1, 10).reshape(3,3)

print("\nOur second array is : \n", array2)

#addition of two array using add() method

addition = np.add(array1, array2)
print("\nAddition of two array is : \n", addition)

#subtraction of two array using substract() method

subtraction  = np.subtract(array1, array2)
print("\nSubtraction  of two array is : \n", subtraction )

#multiplication of two array using multiply() method

multiplication  = np.multiply(array1, array2)
print("\nMultiplication  of two array is : \n", multiplication )

#division of two array using divide() method

division  = np.divide(array1, array2)
print("\nDivision of two array is : \n", division )

#transpose of given array is
#transpose of 1st array
print("\nOriginal array is :\n", array1)

t = array1.transpose()
print("\nTranspose of the array is : \n", t)



Our first array is : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Our second array is : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Addition of two array is : 
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

Subtraction  of two array is : 
 [[0 0 0]
 [0 0 0]
 [0 0 0]]

Multiplication  of two array is : 
 [[ 1  4  9]
 [16 25 36]
 [49 64 81]]

Division of two array is : 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Original array is :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Transpose of the array is : 
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


# * Unary operators

It includes following functions

1.min()

2.max()

3.sum()

In [137]:
import numpy as np
 
arr = np.array([[1, 5, 6], [4, 7, 2],[3, 1, 9]])
print("\nThe given array is : \n", arr)

# to find maximum element of array
large = arr.max()
print ("\nLargest element is:", large)

#to print row wise maximum element we have to use parameter axis
row_large = arr.max(axis = 1)
print ("\nRow-wise maximum elements:", row_large)
 
# To find minimum element of array
small = arr.min(axis = 0)
print ("\nColumn-wise minimum elements:", small)
 
# To find sum of array elements
sum_array = arr.sum()
print ("\nSum of all array elements:", sum_array)

#axis wise sum
sum_array = arr.sum(axis = 0)
print ("\nSum of all array elements:", sum_array)


The given array is : 
 [[1 5 6]
 [4 7 2]
 [3 1 9]]

Largest element is: 9

Row-wise maximum elements: [6 7 9]

Column-wise minimum elements: [1 1 2]

Sum of all array elements: 38

Sum of all array elements: [ 8 13 17]


# * NumPy - Statistical Functions

It includes 
1. median()
2. mean()
3. average()
4. Standard Deviation/std()
5. Variance/var()
6. square root/ sqrt()

# 1. median()

- Median is defined as the value separating the higher half of a data sample from the lower half.

In [147]:
import numpy as np 
# creating array
a = np.array([[30,65,70],[80,95,10],[50,90,60]]) 

print("\nOur array is:\n", a)  

# calculate the median of array
med = np.median(a)
print("\nMedian of an array is: \n" , med)

#Applying median() function along axis 0 (column wise)
med1 = np.median(a, axis = 0) 
print("\nMedian along axis = 0 is : \n", med1) 
 
#Applying median() function along axis 1 (row wise)
med2 = np.median(a, axis = 1)
print("\nMedian along axis = 1 is : \n", med2) 


Our array is:
 [[30 65 70]
 [80 95 10]
 [50 90 60]]

Median of an array is: 
 65.0

Median along axis = 0 is : 
 [50. 90. 60.]

Median along axis = 1 is : 
 [65. 80. 60.]


# 2. mean()

- Arithmetic mean is the sum of elements along an axis divided by the number of elements

In [148]:
import numpy as np 
# creating array
a = np.array([[30,65,70],[80,95,10],[50,90,60]]) 

print("\nOur array is:\n", a)  

# calculate the mean of array
m = np.mean(a)
print("\nMean of an array is: \n" , m)

#Applying mean() function along axis 0 (row wise)
m1 = np.mean(a, axis = 0) 
print("\nMean along axis = 0 is : \n", m1) 
 
#Applying mean() function along axis 1 (column wise)
m2 = np.mean(a, axis = 1)
print("\nMean along axis = 1 is : \n", m2) 


Our array is:
 [[30 65 70]
 [80 95 10]
 [50 90 60]]

Mean of an array is: 
 61.111111111111114

Mean along axis = 0 is : 
 [53.33333333 83.33333333 46.66666667]

Mean along axis = 1 is : 
 [55.         61.66666667 66.66666667]


# 3. average()

- Weighted average is an average resulting from the multiplication of each component by a factor reflecting its importance. 

In [149]:
import numpy as np 
# creating array
a = np.array([1,2,3,4]) 

print("\nOur array is: \n", a)

#Applying average() function

avg = np.average(a) 
print("\nAverage of given array is  : ", avg)  



Our array is: 
 [1 2 3 4]

Average of given array is  :  2.5


# 4. Standard Deviation/std()

- Standard deviation is the square root of the average of squared deviations from mean

* std = sqrt(mean(abs(x - x.mean())**2))

In [150]:
import numpy as np 
# creating array
a = np.array([1,2,3,4]) 

print("\nOur array is: \n", a)

#Applying std() function

deviation = np.std(a) 
print("\nDeviation of given array is  : ", deviation) 


Our array is: 
 [1 2 3 4]

Deviation of given array is  :  1.118033988749895


# 5. Variance/var()

- Variance is the average of squared deviations

- mean(abs(x - x.mean())**2)

In [151]:
import numpy as np 
# creating array
a = np.array([1,2,3,4]) 

print("\nOur array is: \n", a)

#Applying var() function

variation = np.var(a) 
print("\nVariation of given array is  : ", variation) 


Our array is: 
 [1 2 3 4]

Variation of given array is  :  1.25


# 6. square root/ sqrt()

- It return square root of array element

In [155]:
import numpy as np 
# creating array
a = np.array([16, 5, 7]) 

print("\nOur array is: \n", a)

#Applying sqrt() function
sqrt_no = np.sqrt(a) 
print("\nSquare roo of given array is  : \n", sqrt_no) 


Our array is: 
 [16  5  7]

Square roo of given array is  : 
 [4.         2.23606798 2.64575131]


# * NumPy - Indexing & Slicing

# 1. Indexing

- Array indexing is the same as accessing an array element.
- You can access an array element by referring to its index number.

- The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

In [157]:
import numpy as np
# creating array
arr = np.array([1, 2, 3, 4])
#getting first element of array
print("\nFirst element of array is : ", arr[0])


First element of array is :  1


In [163]:
import numpy as np
# creating array of 50 elements
a = np.arange(1, 51).reshape(10, 5)
print("\nOur array is : \n", a)


Our array is : 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]
 [41 42 43 44 45]
 [46 47 48 49 50]]


- To get complete row for specific index

In [165]:
print("Element of rows on index 3 is : \n", a[3])

Element of rows on index 3 is : 
 [16 17 18 19 20]


* To get both row and column of specific index

In [169]:
print("Element is : \n", a[2, 4])

Element is : 
 15


# 2. Slicing

- Slicing in python means taking elements from one given index to another given index.

- We pass slice instead of index like this: [start:end].

- We can also define the step, like this: [start:end:step].

- If we don't pass start its considered 0

- If we don't pass end its considered length of array in that dimension

- If we don't pass step its considered 1

In [173]:
import numpy as np
#Creating array of 7 elements
arr = np.array([1, 2, 3, 4, 5, 6, 7])

#Slice elements from index 1 to index 5
print("\nArray after slicing is : \n", arr[1:5])


Array after slicing is : 
 [2 3 4 5]


In [170]:
import numpy as np
# creating array of 50 elements
a = np.arange(1, 51).reshape(10, 5)
print("\nOur array is : \n", a)


Our array is : 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]
 [41 42 43 44 45]
 [46 47 48 49 50]]


* To get specific element from row and column

In [176]:
print("Row wise elements are : \n", a[2:4])

Row wise elements are : 
 [[11 12 13 14 15]
 [16 17 18 19 20]]


In [177]:
print("Row and column wise elements are : \n", a[2:4, 1:3])

Row and column wise elements are : 
 [[12 13]
 [17 18]]


In [178]:
print("Column wise elements are : \n", a[:,2:4])

Column wise elements are : 
 [[ 3  4]
 [ 8  9]
 [13 14]
 [18 19]
 [23 24]
 [28 29]
 [33 34]
 [38 39]
 [43 44]
 [48 49]]


* Using step in parameters

In [179]:
print("Row and column wise elements are : \n", a[2:4, 1:3:2])

Row and column wise elements are : 
 [[12]
 [17]]


# Negative Slicing

- Slice from the index 3 from the end to index 1 from the end:

In [181]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])
print("\nOriginal array is :\n", arr)
slicing = arr[-3:-1]
print("\nArray after negative slicing : \n", slicing)


Original array is :
 [1 2 3 4 5 6 7]

Array after negative slicing : 
 [5 6]


# * NumPy Joining Array

- Joining means putting contents of two or more arrays in a single array.

- numpy.concatenate((a1, a2, ...), axis)  

In [2]:
import numpy as np
# creating first array
arr1 = np.array([1, 2, 3])
print("\nFirst array is : \n", arr1)

# creating second array
arr2 = np.array([4, 5, 6])
print("\nSecond array is : \n", arr2)

#Joins two array
arr = np.concatenate((arr1, arr2))

print("\nArray after joining is : \n", arr)


First array is : 
 [1 2 3]

Second array is : 
 [4 5 6]

Array after joining is : 
 [1 2 3 4 5 6]


- Joining 2-D array

In [8]:
import numpy as np
# Creating two arrays 
a = np.arange(1,17).reshape(4,4)
print("\nFirst array is : \n", a)

# Creating another array
b = np.arange(17,33).reshape(4,4)
print("\nSecond array is : \n", b)

#Joins two array
combination1 = np.concatenate((a, b), axis = 1) #column wise

combination2 = np.concatenate((a, b), axis = 0) #row wise

print("\nArray after column wise joining is : \n", combination1)

print("\nArray after row wise joining is : \n", combination2)


First array is : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Second array is : 
 [[17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]

Array after column wise joining is : 
 [[ 1  2  3  4 17 18 19 20]
 [ 5  6  7  8 21 22 23 24]
 [ 9 10 11 12 25 26 27 28]
 [13 14 15 16 29 30 31 32]]

Array after row wise joining is : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


# - Joining array using stack functions


- It includes 
1. stack()
2. hstack()
3. vstack()

# 1. stack() 

- We pass a sequence of arrays that we want to join to the stack() method along with the axis.

In [10]:
import numpy as np
# creating first array
arr1 = np.array([1, 2, 3])
print("\nFirst array is : \n", arr1)

# creating second array
arr2 = np.array([4, 5, 6])
print("\nSecond array is : \n", arr2)

#Joins two array
arr = np.stack((arr1, arr2))

print("\nArray after joining is : \n", arr)


First array is : 
 [1 2 3]

Second array is : 
 [4 5 6]

Array after joining is : 
 [[1 2 3]
 [4 5 6]]


# 2. hstack() :

- hstack() to stack along rows.

In [11]:
import numpy as np
# creating first array
arr1 = np.array([1, 2, 3])
print("\nFirst array is : \n", arr1)

# creating second array
arr2 = np.array([4, 5, 6])
print("\nSecond array is : \n", arr2)

#Joins two array
arr = np.hstack((arr1, arr2))

print("\nArray after joining is : \n", arr)


First array is : 
 [1 2 3]

Second array is : 
 [4 5 6]

Array after joining is : 
 [1 2 3 4 5 6]


# 3. vstack()

- vstack()  to stack along columns.

In [12]:
import numpy as np
# creating first array
arr1 = np.array([1, 2, 3])
print("\nFirst array is : \n", arr1)

# creating second array
arr2 = np.array([4, 5, 6])
print("\nSecond array is : \n", arr2)

#Joins two array
arr = np.vstack((arr1, arr2))

print("\nArray after joining is : \n", arr)


First array is : 
 [1 2 3]

Second array is : 
 [4 5 6]

Array after joining is : 
 [[1 2 3]
 [4 5 6]]


# * NumPy Splitting Array

- Splitting is reverse operation of Joining.
- Splitting breaks one array into multiple.

In [16]:
import numpy as np
 
a = np.arange(1,17).reshape(4,4)
print("\nFirst array is : \n", a)

# splitting array
split_array  = np.split(a, 2)
print("\nSplitted array is : \n ", split_array)


First array is : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Splitted array is : 
  [array([[1, 2, 3, 4],
       [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])]


- splitting axis wise

In [17]:
import numpy as np
 
a = np.arange(1,17).reshape(4,4)
print("\nFirst array is : \n", a)

# splitting array
split_array  = np.split(a, 2, axis = 1)
print("\nSplitted array is : \n ", split_array)


First array is : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Splitted array is : 
  [array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16]])]


- we can also splitt by giving specific index

In [19]:
import numpy as np
# creating first array
arr1 = np.array([11, 22, 33, 55, 77, 88])
print("\nOur array is : \n", arr1)

s = np.split(arr1, [1, 4])
print("\nSplitted array from specific index : \n", s)


Our array is : 
 [11 22 33 55 77 88]

Splitted array from specific index : 
 [array([11]), array([22, 33, 55]), array([77, 88])]


# * Uniform Distribution

- Used to describe probability where every event has equal chances of occuring.

In [30]:
import numpy as np

x = np.random.uniform(size=(2, 3))

print("\nUniform distribution is  :\n", x)


Uniform distribution is  :
 [[0.35791199 0.75180069 0.5499788 ]
 [0.21427503 0.1443917  0.92782965]]


# * Normal Distribution

It has three parameters:

loc - (Mean) where the peak of the bell exists.

scale - (Standard Deviation) how flat the graph distribution should be.

size - The shape of the returned array.

In [32]:
import numpy as np
x = np.random.normal(size=(2, 3))

print("\nNormal distribution is  :\n", x)


Normal distribution is  :
 [[-2.70744266  0.52660553  0.63955233]
 [ 1.11610575 -0.16143204  0.73118651]]


- With parameters

In [35]:
import numpy as np
x = np.random.normal(loc=1, scale=2, size=(2, 3))

print("\nNormal distribution is  :\n", x)


Normal distribution is  :
 [[2.23418009 3.34839238 3.06489241]
 [3.31374865 2.85085347 2.96059197]]


# * NumPy - String Functions

- All string method from python we can use here in numpy
1. add()
2. multiply()
3. centre()
4. lower() etc.

In [39]:
import numpy as np
  
# create the arrays
x1 = ['Hello']
x2 = ['World']
print("The 1st array is : ", x1)

print("The 2nd arrays is : ",x2)
  
# using the char.add() method
# here char is module use to perform operation on string
result = np.char.add(x1, x2)
print("\nThe concatenated array is :", result)

The 1st array is :  ['Hello']
The 2nd arrays is :  ['World']

The concatenated array is : ['HelloWorld']


In [40]:
result = np.char.lower(x1)
print("\nThe concatenated array is :", result)


The concatenated array is : ['hello']


In [42]:
result = np.char.upper(x2)
print("\nThe concatenated array is :", result)


The concatenated array is : ['WORLD']
